Weird broken state where host/guest interface mismatch is causing error
    RibosomeError: Wasm runtime error while working with Ribosome: RuntimeError: WasmError { file: ".../holochain_wasmer_host-0.0.84/src/env.rs", line: 95, error: Serialize(Deserialize("invalid type: map, expected variant identifier")) }